---
- name: Create build directory
  ansible.builtin.file:
    path: ~/build_srcds
    state: directory
    mode: "0777"

- name: Build sourcemod
  ansible.builtin.include_role:
    name: sourcemod

- name: Copy build sources
  ansible.builtin.synchronize:
    src: ./
    dest: ~/build_srcds/
    archive: false
    recursive: true

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ dockerhub.username }}"
    password: "{{ dockerhub.password }}"

- name: Build leighmacdonald/uncletopia-srcds image
  community.docker.docker_image:
    name: leighmacdonald/uncletopia-srcds:casual
    tag: latest
    source: build
    force_tag: true
    push: true
    force_source: true
    build:
      nocache: true
      pull: true
      rm: true
      dockerfile: Dockerfile
      path: ~/build_srcds/
    state: present
