---
- name: Install wireguard package
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
    state: present
    pkg:
      - wireguard

- name: /etc/wireguard
  become: true
  ansible.builtin.file:
    path: /etc/wireguard
    mode: 0700

- name: Wg.conf server
  become: true
  ansible.builtin.template:
    src: srv-wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0700
  when: not is_vpn_client | bool

- name: Wg.conf client
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0700
  when: is_vpn_client | bool

- name: Wg-fw
  become: true
  ansible.builtin.ufw:
    rule: allow
    port: "{{ vpn_port }}"
    proto: udp

- name: Systemd reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Systemctl enable wg-quick@wg0
  become: true
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true
